deepspeed --include localhost:0,1,2,3 --master_port=29500 src/train.py \
    --stage sft \
    --model_name_or_path /data0/pretrained-models/Qwen2-7B-Instruct \
    --template qwen \
    --do_train \
    --dataset small_data \
    --finetuning_type full \
    --output_dir /data4/sft_output/qwen2-instruct \
    --overwrite_cache \
    --cache_dir /data4/sft_output/cache_dir \
    --overwrite_output_dir \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --preprocessing_num_workers 16 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --max_grad_norm 1.0 \
    --optim_args 'min_lr_ratio=0.1' \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.01 \
    --logging_steps 2 \
    --save_strategy "steps" \
    --save_steps 50 \
    --eval_strategy "steps" \
    --val_size 0.05 \
    --eval_steps 5 \
    --cutoff_len 2048 \
    --num_train_epochs 0.02 \
    --plot_loss \
    --bf16 true \
    --deepspeed train_bash/deepspeed2.json \
    --report_to "none" \
    --flash_attn fa2 